### ISSUE TITLE
Could not install the plugin in cordova 4.2.0

### ISSUE THREAD

**Issue by dinesh36** [louisbl/cordova-plugin-locationservices#3] opened 2015-08-18 10:25 UTC
Trying to install this plugin in sample project but got the following error while installing the plugin

`cordova plugin add fr.louisbl.cordova.locationservices
Fetching plugin "fr.louisbl.cordova.locationservices" via plugin registry
Installing "fr.louisbl.cordova.locationservices" for android
Error during processing of action! Attempting to revert...
Failed to install 'fr.louisbl.cordova.locationservices':Error: Uh oh!
ENOENT, no such file or directory '/dinesh/WorkSpace/OfficeWork/BizFlirt/testForLocation/hello/platforms/android/local.properties'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at Object.createEditor (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/properties-parser/index.js:328:39)
    at Object.module.exports.getProjectSdkDir (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:172:49)
    at module.exports.framework.install (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:120:46)
    at Object.ActionStack.process (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:72:25)
    at handleInstall (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:591:20)
    at /usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:340:28
    at _fulfilled (/usr/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/cordova/node_modules/q/q.js:816:30)
Error: Uh oh!
ENOENT, no such file or directory '/dinesh/WorkSpace/OfficeWork/BizFlirt/testForLocation/hello/platforms/android/local.properties'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at Object.createEditor (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/properties-parser/index.js:328:39)
    at Object.module.exports.getProjectSdkDir (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:172:49)
    at module.exports.framework.install (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:120:46)
    at Object.ActionStack.process (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:72:25)
    at handleInstall (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:591:20)
    at /usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:340:28
    at _fulfilled (/usr/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/cordova/node_modules/q/q.js:816:30)`

**Comment by louisbl** [comment] 2015-11-21 19:55
Duplicate of #2. You may need to update your Cordova version or fix your Android SDK installation.

**Closed as completed by louisbl** 2015-11-21 19:55 UTC
Labels: duplicate
